### ISSUE TITLE
使用ftp网络位置时  报错 

### ISSUE THREAD

**Issue by sklp** [mymagadsl/cptool#6]
试过0.44 0.5 版本 都不行

**Comment by mymagadsl** [comment]
已經修改過了,但還是無法確定您的 FTP 不支援的問題是什麼,也許是帳號密碼的問題

________________________________
From: sklp ***@***.***>
Sent: Friday, July 16, 2021 9:46:35 PM
To: mymagadsl/cptool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mymagadsl/cptool] 使用ftp网络位置时 报错 (#6)


试过0.44 0.5 版本 都不行

―

**Comment by mymagadsl** [comment]
另外 FTP 支援功能本身不是我開發的目的,這裡由於無法測試(FTP上傳太慢了,大部分人幾乎不會使用它),所以針對此問題本應用程式已經放棄檢修該功能

針對 SMB (網路芳鄰 \\ 開頭的部分,已經有朋友測試可以正常運作沒問題)

若您有其他的方法解決,歡迎分享

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________
From: sklp ***@***.***>
Sent: Friday, July 16, 2021 9:46:35 PM
To: mymagadsl/cptool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mymagadsl/cptool] 使用ftp网络位置时 报错 (#6)


试过0.44 0.5 版本 都不行

―
