### ISSUE TITLE
取消等待複製完成在再續耕，只有第一次續耕有效果

### ISSUE THREAD

**Issue by sd016808** [mymagadsl/cptool#7]
如標題所述，使用的版本為0.50的版本，當要進行第三塊耕地的時候，畫面會一直卡在
![image](https://user-images.githubusercontent.com/9477727/126024839-44fd31bf-8a82-4c8e-b180-d67021647afd.png)

會一直卡直到之前的地搬移成功，但第二塊地的時候是正常的，階段四完成後馬上就開始下一塊地的階段一

**Comment by mymagadsl** [comment]
首先告知, CTPool  單純只是一個 chia-plotter 的下指令輔助工具(因為他只有DOS指令的功能,沒有GUI)

這個功能是 CPTool 針對 chia-plotter 下了 -w, --waitforcopy    Wait for copy to start next plot 這個指令(我的應用程式只有下指令的功能),您可以每次執行耕地的時候仔細看下方的程式執行結果區,會有一串指令用來告訴 chia-plotter 該怎麼動作的指令

![w](https://user-images.githubusercontent.com/6682942/126091658-71b8c8c0-14c4-49b1-978b-83a9de49bb9f.png)
 
所以目前這個 -w 指令造成的BUG 並非我能處理的,請轉移到 https://github.com/stotiks/chia-plotter 作者那邊詢問.

另外,我本身耕地都是會打勾這個選項,目前為止每次都會等待複製完畢才續耕,並沒有發生過自動續耕(單純個人經驗,每個人碰到狀況不同)

再請您測試看看是否為其他問題.
